DataFlowAnalysis/DataFlowAnalysis

tests/org.palladiosimulator.dataflow.confidentiality.analysis.tests/src/org/palladiosimulator/dataflow/confidentiality/analysis/ConstraintTest.java
This PR adds very simple printing of debugging information to the constraint tests. This is used in #18. It shall be refactored later, when we look at #12.
=> Add simple debug information printing to constraint tests

bundles/org.palladiosimulator.dataflow.confidentiality.analysis/META-INF/MANIFEST.MF
Exports the package `org.palladiosimulator.dataflow.confidentiality.analysis.sequence.pcm` for external use.
=> Adjust analysis manifest

bundles/org.palladiosimulator.dataflow.confidentiality.analysis/src/org/palladiosimulator/dataflow/confidentiality/analysis/sequence/entity/pcm/SEFFActionSequenceElement.java, tests/org.palladiosimulator.dataflow.confidentiality.analysis.tests/src/org/palladiosimulator/dataflow/confidentiality/analysis/sequencefinder/ActionSequenceFinderTest.java
This PR adds the method `isBranching()` to SEFFActionSequenceElements, which determine, whether a SEFF Sequence Element (i.e. StartAction for now) was created due to Branching Behavior in the Model.
This PR closes #37
=> Add Branching to SEFF Elements

README.md, bundles/org.palladiosimulator.dataflow.confidentiality.analysis/src/org/palladiosimulator/dataflow/confidentiality/analysis/DataFlowConfidentialityAnalysis.java, bundles/org.palladiosimulator.dataflow.confidentiality.analysis/src/org/palladiosimulator/dataflow/confidentiality/analysis/core/AbstractStandalonePCMDataFlowConfidentialityAnalysis.java, tests/org.palladiosimulator.dataflow.confidentiality.analysis.tests/src/org/palladiosimulator/dataflow/confidentiality/analysis/BaseTest.java
Fix typo in function `initializeAnalysis`. Update README to reflect the changes after the code review of #52.
=> Fix typo in analysis. Update README.

bundles/org.palladiosimulator.dataflow.confidentiality.analysis/META-INF/MANIFEST.MF
Add the `utils.pcm` package to the exported packages of the analysis.
=> Export analysis utils.

bundles/org.palladiosimulator.dataflow.confidentiality.analysis/src/org/palladiosimulator/dataflow/confidentiality/analysis/builder/pcm/PCMAnalysisBuilderData.java, bundles/org.palladiosimulator.dataflow.confidentiality.analysis/src/org/palladiosimulator/dataflow/confidentiality/analysis/characteristics/node/LegacyPCMNodeCharacteristicsCalculator.java, bundles/org.palladiosimulator.dataflow.confidentiality.analysis/src/org/palladiosimulator/dataflow/confidentiality/analysis/characteristics/node/NodeCharacteristicsCalculator.java, bundles/org.palladiosimulator.dataflow.confidentiality.analysis/src/org/palladiosimulator/dataflow/confidentiality/analysis/characteristics/node/PCMNodeCharacteristicsCalculator.java, bundles/org.palladiosimulator.dataflow.confidentiality.analysis/src/org/palladiosimulator/dataflow/confidentiality/analysis/core/AbstractStandalonePCMDataFlowConfidentialityAnalysis.java, bundles/org.palladiosimulator.dataflow.confidentiality.analysis/src/org/palladiosimulator/dataflow/confidentiality/analysis/resource/ResourceLoader.java
This PR adds validation for node characteristics and preloaded resources to the analysis builder or the analysis itself.
It implements the following features
- Check preloaded resources (i, e, running the analysis with a List of loaded resources). Previously, an internal error could occur, if an important model (e.g. allocation or usage model) was missing. Now, users will receive an error while using the builder
- Check the node characteristics once before running the analysis (This step occurs during Initialization of the analysis, not in the builder, because resources are loaded during the initialization of the analysis and not before)
This PR closes #55
=> Add Node Characteristic and Resource Validation to Builder

tests/org.palladiosimulator.dataflow.confidentiality.analysis.tests/META-INF/MANIFEST.MF
A missing dependency made one test case fail if the test projects (`.test` and `.testmodels`) were loaded in the automatically built eclipse product.
=> Fix test project manifest to work without analysis in the eclipse product.

bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/builder/pcm/PCMAnalysisBuilderData.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/builder/pcm/PCMDataFlowConfidentialityAnalysisBuilder.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/core/StandalonePCMDataFlowConfidentialityAnalysis.java
This PR makes the plugin activator optional, so that the analysis can be used in a project that is already loaded.
This issue closes #79
=> Make activator plugin optional

bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/PCMNodeCharacteristicsCalculator.java, tests/org.dataflowanalysis.analysis.testmodels/models/CompositeCharacteristicsTest/default.nodecharacteristics, tests/org.dataflowanalysis.analysis.testmodels/models/InternationalOnlineShop/default.nodecharacteristics, tests/org.dataflowanalysis.analysis.testmodels/models/NodeCharacteristicsTest/default.nodecharacteristics, tests/org.dataflowanalysis.analysis.testmodels/models/OneAssembyMultipleResourceContainerTest/default.nodecharacteristics, tests/org.dataflowanalysis.analysis.testmodels/models/TravelPlanner/travelPlanner.nodecharacteristics, tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/constraint/ConstraintResultTest.java, tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/constraint/data/ConstraintViolations.java
This PR fixes the typo in the pcm metamodel for resource assignees.
This PR fixes #107
=> Fix typo for resource assignees

.gitignore, bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/core/DFDActionSequenceFinder.java, tests/org.dataflowanalysis.analysis.testmodels/models/OnlineShopDFD/.project, tests/org.dataflowanalysis.analysis.testmodels/models/OnlineShopDFD/.settings/org.eclipse.core.resources.prefs, tests/org.dataflowanalysis.analysis.testmodels/models/OnlineShopDFD/onlineshop.datadictionary, tests/org.dataflowanalysis.analysis.testmodels/models/OnlineShopDFD/onlineshop.dataflowdiagram, tests/org.dataflowanalysis.analysis.testmodels/models/OnlineShopDFDsimple/.project, tests/org.dataflowanalysis.analysis.testmodels/models/OnlineShopDFDsimple/.settings/org.eclipse.core.resources.prefs, tests/org.dataflowanalysis.analysis.testmodels/models/OnlineShopDFDsimple/onlineshop.datadictionary, tests/org.dataflowanalysis.analysis.testmodels/models/OnlineShopDFDsimple/onlineshop.dataflowdiagram, tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/dfd/OnlineShopDFDTest.java
This PR closes #119 and adds two new DFD models: 
* The `OnlineShopDFD` is a replica of the example model from the [web editor](https://dataflowanalysis.github.io/WebEditor/)
* The `OnlineShopDFDsimple` contains three instead of one `User` source because of current limitations of the DFD analysis which would lead to a StackOverflow exception. This should be further investigated in the future.
This PR also adds test cases for the online shop model. This includes basic action sequence extraction, as well as tests on node labels, data labels, and realistic constraints.
=> Add Online Shop DFD models and test case

bundles/org.dataflowanalysis.analysis.converter/src/org/dataflowanalysis/analysis/converter/DataFlowDiagramConverter.java, bundles/org.dataflowanalysis.analysis.converter/src/org/dataflowanalysis/analysis/converter/FileNameOnlyURIHandler.java, bundles/org.dataflowanalysis.analysis.converter/src/org/dataflowanalysis/analysis/converter/MicroSecEndConverter.java, bundles/org.dataflowanalysis.analysis.converter/src/org/dataflowanalysis/analysis/converter/microsecend/MicroSecEnd.java, bundles/org.dataflowanalysis.analysis.converter/src/org/dataflowanalysis/analysis/converter/microsecend/TaggedValuesDeserializer.java, tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/converter/MicroSecEndTest.java
The converter now processes these labels:
- Node Stereotypes
- Node TaggedValues
- Flow  Stereotypes
- Flow TaggedValues
The output behavior is now
Set node stereotypes = true
Set flow stereotypes= true
Set flow taggedValues=true
Forward incoming packages
Labels for node taggedValues are created but not forwarded
=> Enhance MicroSecEnd converter by preserving flow labels

bundles/org.dataflowanalysis.analysis.converter/src/org/dataflowanalysis/analysis/converter/MicroSecEndConverter.java, tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/converter/MicroSecEndTest.java
Ive added non random ids to microsecend models, so that if you converter the same model twice you get the same result.
This makes commits actually readble.
Furthermore I've found and addressed a bug where if you convert multiple models with the same converter, they share hashmaps.
=> Non random ids for microsecend models and fixed hidden state bug

bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/core/DFDTransposeFlowGraph.java, bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/core/DFDTransposeFlowGraphFinder.java, bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/core/DFDVertex.java, bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/AbstractPCMVertex.java, bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/PCMVertexCharacteristicsCalculator.java, bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/finder/PCMSEFFTransposeFlowGraphFinder.java, bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/finder/PCMTransposeFlowGraphFinder.java, bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/finder/PCMUserTransposeFlowGraphFinder.java, bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/seff/CallingSEFFPCMVertex.java, bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/seff/SEFFPCMVertex.java, bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/user/CallingUserPCMVertex.java, bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/user/UserPCMVertex.java, bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/utils/PCMQueryUtils.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/DataFlowAnalysisBuilder.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/core/DataCharacteristic.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/core/TransposeFlowGraphFinder.java
This PR updates the transpose flow graph finders of PCM and DFD with the following features:
- Allow finding of transpose flow graphs at a given list of sink nodes
- Allow finding of transpose flow graphs between a list of source and sink nodes
This PR closes #146 and is already used downstream in ABUNAI
=> Update transpose flow graph finders

bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/finder/PCMTransposeFlowGraphFinder.java
In fixing some mistakes in my ABUNAI Implementation, I've discovered that the latest context is required for finding TFGs in PCM that call other methods
=> Allow finding Transpose Flow Graphs with given contexts

bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/DataFlowConfidentialityAnalysis.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/utils/ANSIConsoleLogger.java
This PR adds colorful logger output to mark important information (like possible model warnings).
Especially, in larger models this is rather useful
=> Add colorful logger output

bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/finder/PCMTransposeFlowGraphFinder.java
I thought this feature was already included in #159, but it seems I missed pushing a last commit :wink:.
This PR introduces this feature and fixes the compile issue in https://github.com/abunai-dev/UncertaintyAwareConfidentialityAnalysis/pull/1#pullrequestreview-2093216703
=> Add support for Parameters in PCM TFG Finder

bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/core/DFDFlowGraphCollection.java, bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/PCMFlowGraphCollection.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/core/FlowGraphCollection.java
This PR adds the possibility to delay the initialization of the `FlowGraphCollection` to allow implementations of `findTransposeFlowGraphs()` to use attributes other than the resource provider.
This PR adds functionality required in https://github.com/abunai-dev/UncertaintyAwareConfidentialityAnalysis/pull/3
=> Allow delayed initialization of flow graph collection

bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/seff/SEFFPCMVertex.java
This PR fixes the improper filtering of Start and End Nodes in PCM Branches.
Before this fix, characteristics would have been filtered by their name according to the available parameters of the SEFF signature. This erroneous filtering is removed, and instead characteristics are forwarded as normal
=> Fix improper filtering for PCM Vertices in Branches

bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/core/DFDTransposeFlowGraphFinder.java
In case of a Node sending from at least 3 output pins to a lesser number of input pins of the same node (meaning at least one occurrence of two flows into one pin), the TFG finder did not properly create multiple TFG's, if all output pins require the same input pins.
=> Fix: Edge case in which the heuristics prevented multi flow pins from creating multiple TFGs

bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/DFDDataFlowAnalysisBuilder.java, bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/PCMDataFlowConfidentialityAnalysisBuilder.java
For running the analysis standalone and using the converter properly it is necessary for the analysis to take absolute paths instead of relative plugin paths
=> Feat: Allow analysis to take absolute Paths without activator for both PCM and DFD

bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/resource/ResourceProvider.java
This PR changes the visibility of the function `isInTargetResource` that is called directly from inside the [ABUNAI](https://abunai.dev) scalability evaluation.
=> Fix visibility of ResourceProvider

bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/PCMDataFlowConfidentialityAnalysisBuilder.java, bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/finder/PCMSEFFTransposeFlowGraphFinder.java, bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/seff/CallingSEFFPCMVertex.java, bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/user/CallingUserPCMVertex.java
This PR introduces some fixes for the PCM Flow Graph finder and further fixes an error/warning of the builder when using a custom resource provider
=> PCM Flow Graph Finder Fixes

bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/DFDConfidentialityAnalysis.java, bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/resource/DFDResourceProvider.java, bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/PCMDataFlowConfidentialityAnalysis.java, bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/PCMDataFlowConfidentialityAnalysisBuilder.java, bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/resource/PCMResourceProvider.java, bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/resource/PCMURIResourceProvider.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/resource/ResourceProvider.java
This PR allows the execution of DFD and PCM analyses in environments without an eclipse instance.
For that, the resource loading logic was modified.
Additionally, the resource loader now logs errors that occur while loading the model elements. This change allows developers and users to spot mistakes that prevent the loading of models (like missing elements or dangling references).
This PR progresses #222, but does **not close** the issue, as a CLI interface for the converter and analyses does need to be implemented.
=> Allow execution of DFD and PCM analyses in a non-eclipse environment

README.md, bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/DFDDataFlowAnalysisBuilder.java, bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/interactive/DFDAnalysisCLI.java, bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/resource/DFDURIResourceProvider.java, bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/PCMDataFlowConfidentialityAnalysisBuilder.java, bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/interactive/PCMAnalysisCLI.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/DataFlowAnalysisBuilder.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/VertexSourceSelectors.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/result/DSLResult.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/resource/ResourceProvider.java, tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/dfd/ResourceProviderTest.java
This PR implements a CLI for the DFD and PCM analysis. It supports the following modes:
- Interactive mode: The CLI asks for the files on the Standard Input
- Arguments mode: The CLI takes the required parameters from the arguments passed to the binary
This PR begins progress towards closing #222
=> Allow the execution of the analysis via a CLI

bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/DFDConfidentialityAnalysis.java, bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/DFDDataFlowAnalysisBuilder.java, bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/PCMDataFlowConfidentialityAnalysis.java, bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/PCMDataFlowConfidentialityAnalysisBuilder.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/resource/ResourceProvider.java
This PR adds validation and error messages while loading resources.
This is helpful to catch invalid or (somewhat) broken model files while executing the analysis, as Eclipse simply ignores those errors and tries to fully load the models anyway.
=> Add validation and error logging while loading resources

tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/DemoTest.java
This PR adds a self-contained demo test and thereby resolves #195. As stated in the javadoc:
```
/**
* This class serves as self-contained analysis demonstration using the simple PCM and DFD instances of the online shop.
* The two initialize methods showcase the analysis setup for PCM and DFD, while the test methods show how to analyze
* both PCM and DFD models with and without using the ConstraintDSL, and also how to use the QueryDSL. The high degree
* of code duplication within the tests (e.g., in manual querying) is intended for the sake of self-contained tests.
*/
```
Open tasks:
=> Add demo test

bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/PCMDataFlowConfidentialityAnalysis.java
This PR includes a bugfix to ensure that the resources are set up correctly for every PCM analysis, regardless of being run standalone or in an eclipse environment.
Bugs and errors may occur, as ones did for the DFD analysis in this related comment: https://github.com/DataFlowAnalysis/Converter/pull/32#pullrequestreview-2793979260
=> Setup Resources for every created PCM Analysis

bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/interactive/DFDAnalysisCLI.java, bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/interactive/PCMAnalysisCLI.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/AnalysisConstraint.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/constraint/ConstraintDSL.java, tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/integration/dsl/DSLResultTest.java
This PR implements named constraints, so they can be displayed to the user in a more intuitive manner.
However, there are still some discussion points (please provide your opinion on the following, @01Parzival10 @sebinside @Nicolas-Boltz):
=> Implement Named Constraints

.husky/pre-commit, flake.lock, flake.nix, gitHooks/hooks/pre-commit
This PR adds a pre-commit hook using husky. For using the pre-commit hook, one needs to install the program, then run `husky install`.
Additionally, a Nix Devshell has been added that helps using the project on Nix systems. (This is mostly for me)
=> Add git hook for ensuring formatting

bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/AnalysisConstraint.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/SourceSelectors.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/VertexDestinationSelectors.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/VertexSourceSelectors.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/constraint/DSLNodeDestinationSelector.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/constraint/DSLNodeSourceSelector.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/DataCharacteristicListSelector.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/VertexCharacteristicsListSelector.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/VertexCharacteristicsSelector.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/utils/ParseResult.java, tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/integration/dsl/DSLResultTest.java, tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/integration/dsl/VertexCharacteristicListSelectorTest.java, tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/integration/dsl/VertexSourceSelectorTest.java
This PR fixes issues with parsing and evaluating vertex selectors in the analysis DSL.
This was caused by incorrect evaluation of normal vertex selectors and additionally different necessary evaluation logic for a group of selectors.
Additionally, this PR introduces some tests to prevent regressions.
This PR closes #304
=> Fix issues with parsing and evaluating vertex selectors

bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/AnalysisConstraint.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/ConditionalSelectors.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/DataSourceSelectors.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/SourceSelectors.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/VertexDestinationSelectors.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/VertexSourceSelectors.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/CharacteristicsSelectorData.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/DataCharacteristicListSelector.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/DataCharacteristicsSelector.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/EmptySetOperationConditionalSelector.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/Intersection.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/VariableConditionalSelector.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/VariableNameSelector.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/VertexCharacteristicsListSelector.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/VertexCharacteristicsSelector.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/VertexTypeSelector.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/utils/StringView.java, tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/integration/dsl/SourceSelectorsTest.java
This PR adds modifications in the DSL to allow for the skipping of whitespace characters. Currently, they are mostly allowed at the beginning of selectors and between the different parts of the constraint itself (so between neverFlows, etc.)
Additionally, some tests were modified to test whether whitespace characters are skipped
This should allow for more flexibility with parsing, so the front end needs to clean up less.
This PR closes #309
=> Skip whitespace characters in DSL

docs/.gitignore, docs/download/index.md, docs/package.json, docs/publications/index.md, docs/scripts/prebuild.js
The version now gets fetched in a pre{build, dev} script.
linked to #275
=> Use SSR for version displays in docs

bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/VertexDestinationSelectors.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/constraint/DSLNodeDestinationSelector.java, bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/VertexNameSelector.java, docs/wiki/dsl/index.md, tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/integration/dsl/DSLResultTest.java, tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/integration/dsl/VertexNameSelectorTest.java
This PR adds a DSL Selector with the keyword "named" followed by a name.
This selector matches vertices according to their name.
Additionally, this PR adds corresponding tests and updates the documentation
=> Add DSL Selector for matching vertex names

bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/constraint/DSLDataSourceSelector.java
The created Data Characteristic List Selector when using the Java DSL and inverting it does not create a correct data characteristic list selector.
Instead, it creates an incorrect empty one
=> Fix bug in inverted characteristic list selector in DSL
