- README.md
- dependencies.p2f
This PR adds a small readme that contains a small summary of the project and reference to the external web page of the project.
Furthermore, the readme outlines the install instructions to begin using the project in Eclipse.
Lastly, the readme outlines how the analysis can be used to analyze custom models and provides references to the tests implemented.
Additionally, this PR closes #16
> Short readme for installation and usage

- README.md
- dependencies.p2f
- tests/org.palladiosimulator.dataflow.confidentiality.analysis.tests/META-INF/MANIFEST.MF
This PR add some documentation and an **install file** for the new modelling repository outlined in #10. In my current testing, i have found no issues using the new modelling repository, so i think we can begin using the new model.
As this PR includes the fixes from #22, this PR should be merged after that PR is merged. I will fast-forward this branch, as soon as that PR is merged
This PR closes #10, as i haven't found any issues in the tests and analysis with the new repository
> Use new modeling repository

- dependencies.p2f
This PR adds Developer sources to the install file. This includes the following items:
- Palladio Core Developer Sources
- MDSD Developer Sources
This PR closes #32
> Installfile sources

- .github/workflows/build.yml
- releng/org.palladiosimulator.dataflow.confidentiality.pcm.analysis.targetplatform/org.palladiosimulator.dataflow.confidentiality.pcm.analysis.targetplatform.targetplatform.target
- tests/org.palladiosimulator.dataflow.confidentiality.analysis.tests/src/org/palladiosimulator/dataflow/confidentiality/analysis/constraint/ConstraintResultTest.java
- tests/org.palladiosimulator.dataflow.confidentiality.analysis.tests/src/org/palladiosimulator/dataflow/confidentiality/analysis/propagation/LabelPropagationTest.java
- tests/org.palladiosimulator.dataflow.confidentiality.analysis.tests/src/org/palladiosimulator/dataflow/confidentiality/analysis/sequencefinder/ActionSequenceFinderTest.java
This PR removes the parameterized tests for Constraints, Label and Sequences.
This resolves #44
> Remove parameterized tests

- README.md
- tests/org.palladiosimulator.dataflow.confidentiality.analysis.tests/src/org/palladiosimulator/dataflow/confidentiality/analysis/ReadMeTest.java
Fix issues regarding the application of the analysis in the readme.
I should probably have verified the documentation after the changes in #51
> Fix parameter names and return types of example

- .github/workflows/main.yml
This PR updates the namespace of the update site in the workflow, so it deploys correctly.
> Update namespace in workflow

- bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/entity/pcm/AbstractPCMActionSequenceElement.java
- bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/entity/pcm/PCMActionSequence.java
- bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/entity/pcm/seff/CallingSEFFActionSequenceElement.java
- bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/entity/pcm/seff/SEFFActionSequenceElement.java
- bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/entity/pcm/user/CallingUserActionSequenceElement.java
- bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/entity/pcm/user/UserActionSequenceElement.java
- bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/entity/sequence/AbstractActionSequenceElement.java
- bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/sequence/pcm/finder/PCMSEFFFinderUtils.java
- bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/sequence/pcm/finder/PCMUserFinderUtils.java
- tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/AnalysisUtils.java
- tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/constraint/data/ConstraintViolations.java
- tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/propagation/LabelPropagationCharacteristics.java
- tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/sequencefinder/ActionSequenceFinderPaths.java
- tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/sequencefinder/ActionSequenceFinderTest.java
This PR generates action sequence elements for start and stop actions in User and SEFF elements. Furthermore, it fixes the propagation bug outlined in #78
> Fix propagation bug

- bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/core/pcm/user/UserActionSequenceElement.java
actions can be in branches, too ;)
> Fix null pointer exception in PCM user action toString()

- tests/org.dataflowanalysis.analysis.testmodels/models/IgnoredNodeTest/.project
- tests/org.dataflowanalysis.analysis.testmodels/models/IgnoredNodeTest/default.allocation
- tests/org.dataflowanalysis.analysis.testmodels/models/IgnoredNodeTest/default.nodecharacteristics
- tests/org.dataflowanalysis.analysis.testmodels/models/IgnoredNodeTest/default.repository
- tests/org.dataflowanalysis.analysis.testmodels/models/IgnoredNodeTest/default.resourceenvironment
- tests/org.dataflowanalysis.analysis.testmodels/models/IgnoredNodeTest/default.system
- tests/org.dataflowanalysis.analysis.testmodels/models/IgnoredNodeTest/default.usagemodel
- tests/org.dataflowanalysis.analysis.testmodels/models/IgnoredNodeTest/dic.pddc
- tests/org.dataflowanalysis.analysis.testmodels/models/IgnoredNodeTest/representations.aird
- tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/constraint/ConstraintFeatureTest.java
This PR adds a test model with test to check whether the label propagation still works, when an unknown node is encountered
> Add test and testmodel for unknown seff actions

- tests/org.dataflowanalysis.analysis.testmodels/models/CompositeCharacteristicsTest/default.nodecharacteristics
- tests/org.dataflowanalysis.analysis.testmodels/models/InternationalOnlineShop/default.nodecharacteristics
- tests/org.dataflowanalysis.analysis.testmodels/models/NodeCharacteristicsTest/default.nodecharacteristics
- tests/org.dataflowanalysis.analysis.testmodels/models/OneAssembyMultipleResourceContainerTest/default.nodecharacteristics
- tests/org.dataflowanalysis.analysis.testmodels/models/ReturnTestModel/default.nodecharacteristics
- tests/org.dataflowanalysis.analysis.testmodels/models/TravelPlanner/travelPlanner.nodecharacteristics
This PR adds ids for node characteristics
> Add ids for all nodecharacteristics entries

- bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/DFDConfidentialityAnalysis.java
- bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/DFDDataFlowAnalysisBuilder.java
- bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/PCMDataFlowConfidentialityAnalysis.java
- bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/PCMDataFlowConfidentialityAnalysisBuilder.java
This PR makes several private attributes of DFD and PCM analysis and builder protected to make them usable in inherited classes.
> Change visibility in analysis and builder to enable inheritance.

- bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/PCMDataFlowConfidentialityAnalysisBuilder.java
This PR uses the validation logic from previous PRs and actually calls the behavior. This PR closes #118
> Validate data in PCM Builder

- bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/DFDConfidentialityAnalysis.java
- bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/PCMDataFlowConfidentialityAnalysis.java
- bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/DataFlowAnalysisBuilder.java
- bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/DataFlowConfidentialityAnalysis.java
- tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/BaseTest.java
> [!IMPORTANT] 
> This PR is dependent on #123 and thus needs to be merged afterwards
This PR adds unified logging for both analyses in this repo. The proposed logging format is:
```
Timestamp [Level] Classname - Message
```
An example would be:
```
12 [INFO] PCMConfidentialityAnalysis - Loaded model elements from files
```
This PR closes #126
> Add Unified Logging for PCM and DFD Analyses

- bundles/org.dataflowanalysis.analysis.converter/src/org/dataflowanalysis/analysis/converter/Converter.java
- bundles/org.dataflowanalysis.analysis.converter/src/org/dataflowanalysis/analysis/converter/FileNameOnlyURIHandler.java
- tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/converter/WebEditorTest.java
Fixes the issue of hardcoded relative paths in the data flow diagram #131
> Remove relative path from DFD

- bundles/org.dataflowanalysis.analysis.converter/src/org/dataflowanalysis/analysis/converter/MicroSecEndConverter.java
- bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/seff/CallingSEFFPCMVertex.java
- bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/seff/SEFFPCMVertex.java
- bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/user/CallingUserPCMVertex.java
- bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/user/UserPCMVertex.java
- tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/converter/MicroSecEndTest.java
@uuqjz You added an assignment template which was never removed in case of an empty output pin list
> Fixing emtpy assignment issue

- bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/seff/CallingSEFFPCMVertex.java
- bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/core/user/CallingUserPCMVertex.java
This PR fixes the hash code of calling PCM elements
> Fix hash code of calling elements

- bundles/org.dataflowanalysis.analysis.dfd/META-INF/MANIFEST.MF
- bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/core/DFDFlowGraphCollection.java
- bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/simple/DFDSimpleTransposeFlowGraph.java
- bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/simple/DFDSimpleTransposeFlowGraphFinder.java
- bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/simple/DFDSimpleVertex.java
- tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/dfd/simple/DFDSimpleTest.java
DFD TFG finder and logic for DFDs with number of assumptions that are verified
> Simpledfd Finder for less complex DFDs

- bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/core/DFDTransposeFlowGraphFinder.java
Next time i really have to make sure the branch name has no uppercase letters
> Fix: Ban terminal cycles

- .github/workflows/main.yml
- pom.xml
This PR updates tycho to the newest version to allow for parameterized tests in the future
> Update tycho to newest version

- bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/core/DFDVertex.java
Should close https://github.com/DataFlowAnalysis/DataFlowAnalysis/issues/240
> Fix: Fix inconsistency issue by using LinkedHashMap instead of HashMap for linking outPin to outgoing Labels

- .github/workflows/main.yml
- tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/dfd/MicroSecEndTest.java
Must be merged after ExampleModels PR15
> Use map from examplemodels instead of duplicate

- bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/PCMDataFlowConfidentialityAnalysisBuilder.java
- bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/utils/PCMQueryUtils.java
- bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/resource/ResourceProvider.java
This PR runs the formatter on some new changes that were introduced while the PR enforcing the formatter pipeline was waiting
> Run formatter on new changes

- bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/DataCharacteristicsSelector.java
This PR fixes an important issue with the data characteristic selector in the DSL
> Hotfix: Fix wrong results with data characteristics selector

- pom.xml
- releng/org.dataflowanalysis.analysis.targetplatform/org.dataflowanalysis.analysis.targetplatform.targetplatform.target
- tests/org.dataflowanalysis.analysis.tests/META-INF/MANIFEST.MF
This PR reenables the tests, so they can be tested against to again
> Reenable tests

- docs/publications/bib.js
Provided bib entry for website about analysis coupling using xDECAF
> Update bib.js with TSE Reiche entry

- bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/core/DFDVertex.java
- tests/org.dataflowanalysis.analysis.tests/src/org/dataflowanalysis/analysis/tests/integration/dfd/MicroSecEndTest.java
GetVertices was not listing all vertices when cyclic
> Fix: GetVertices not listing all vertices when cyclic
